#!/bin/sh /etc/rc.common

START=96
STOP=16
USE_PROCD=1

load_drv(){
    logger -t 4gmodem "load driver"
    procd_open_instance load_drv
    procd_set_param command /usr/libexec/load_drv.sh $1
    procd_close_instance
}

start_service() {
    logger -t 4gmodem "load driver"
    config_load 4gmodem
    config_foreach load_drv modem
}
